apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1: Encrypted secrets via ksops/kustomize
    - repoURL: https://github.com/goksel/nix-config
      targetRevision: HEAD
      path: manifests/apps/tailscale-operator
      # Kustomize enables ksops generator
    # Source 2: Helm chart
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.78.3
      helm:
        valuesObject:
          oauth:
            # References secret created by ksops
            clientIdSecretName: operator-oauth
            clientIdSecretKey: client_id
            clientSecretSecretName: operator-oauth
            clientSecretSecretKey: client_secret
          operatorConfig:
            defaultTags:
              - "tag:k8s-operator"
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
